from app import db
from app.models import FoodItem
from datetime import datetime

def initialize_default_data():
    """Initialize default Ugandan food items"""
    
    # Check if data already exists
    if FoodItem.query.first():
        return
    
    ugandan_foods = [
        {
            'name': 'Matooke (Plantain)',
            'local_name': 'Matooke',
            'category': 'grains',
            'description': 'Staple food in Uganda, rich in carbohydrates and fiber',
            'calories': 122,
            'protein': 1.3,
            'carbohydrates': 31.9,
            'fiber': 2.3,
            'fat': 0.4,
            'sugar': 15.0,
            'glycemic_index': 45,
            'sodium': 4,
            'vitamin_c': 18.4,
            'iron': 0.6,
            'calcium': 3,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'current_price': 3000,
            'price_unit': 'kg'
        },
        {
            'name': 'Sweet Potatoes',
            'local_name': 'Binyebwa',
            'category': 'vegetables',
            'description': 'Nutritious root vegetable, high in fiber and beta-carotene',
            'calories': 86,
            'protein': 1.6,
            'carbohydrates': 20.1,
            'fiber': 3.0,
            'fat': 0.1,
            'sugar': 4.2,
            'glycemic_index': 70,
            'sodium': 54,
            'vitamin_c': 2.4,
            'iron': 0.7,
            'calcium': 30,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'current_price': 2000,
            'price_unit': 'kg'
        },
        {
            'name': 'Beans',
            'local_name': 'Binyebwa',
            'category': 'proteins',
            'description': 'Excellent source of plant protein and fiber',
            'calories': 347,
            'protein': 21.6,
            'carbohydrates': 62.4,
            'fiber': 15.2,
            'fat': 1.2,
            'sugar': 2.1,
            'glycemic_index': 29,
            'sodium': 12,
            'vitamin_c': 4.5,
            'iron': 8.2,
            'calcium': 113,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'weight_gain_friendly': True,
            'current_price': 4000,
            'price_unit': 'kg'
        },
        {
            'name': 'Groundnuts (Peanuts)',
            'local_name': 'Binyebwa',
            'category': 'proteins',
            'description': 'High in protein and healthy fats',
            'calories': 567,
            'protein': 25.8,
            'carbohydrates': 16.1,
            'fiber': 8.5,
            'fat': 49.2,
            'sugar': 4.7,
            'glycemic_index': 13,
            'sodium': 18,
            'vitamin_c': 0,
            'iron': 4.6,
            'calcium': 92,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_gain_friendly': True,
            'current_price': 5000,
            'price_unit': 'kg'
        },
        {
            'name': 'Cabbage',
            'local_name': 'Kabage',
            'category': 'vegetables',
            'description': 'Low calorie vegetable, rich in vitamin C and fiber',
            'calories': 25,
            'protein': 1.3,
            'carbohydrates': 5.8,
            'fiber': 2.5,
            'fat': 0.1,
            'sugar': 3.2,
            'glycemic_index': 10,
            'sodium': 18,
            'vitamin_c': 36.6,
            'iron': 0.5,
            'calcium': 40,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'current_price': 1500,
            'price_unit': 'piece'
        },
        {
            'name': 'Tomatoes',
            'local_name': 'Enyanya',
            'category': 'vegetables',
            'description': 'Rich in lycopene and vitamin C',
            'calories': 18,
            'protein': 0.9,
            'carbohydrates': 3.9,
            'fiber': 1.2,
            'fat': 0.2,
            'sugar': 2.6,
            'glycemic_index': 15,
            'sodium': 5,
            'vitamin_c': 13.7,
            'iron': 0.3,
            'calcium': 10,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'current_price': 2000,
            'price_unit': 'kg'
        },
        {
            'name': 'Onions',
            'local_name': 'Tungulu',
            'category': 'vegetables',
            'description': 'Low calorie, adds flavor to meals',
            'calories': 40,
            'protein': 1.1,
            'carbohydrates': 9.3,
            'fiber': 1.7,
            'fat': 0.1,
            'sugar': 4.2,
            'glycemic_index': 15,
            'sodium': 4,
            'vitamin_c': 7.4,
            'iron': 0.2,
            'calcium': 23,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'current_price': 2500,
            'price_unit': 'kg'
        },
        {
            'name': 'Rice',
            'local_name': 'Mpunga',
            'category': 'grains',
            'description': 'Staple grain, good source of energy',
            'calories': 130,
            'protein': 2.7,
            'carbohydrates': 28.0,
            'fiber': 0.4,
            'fat': 0.3,
            'sugar': 0.1,
            'glycemic_index': 73,
            'sodium': 1,
            'vitamin_c': 0,
            'iron': 0.8,
            'calcium': 28,
            'is_affordable': True,
            'diabetes_friendly': False,
            'weight_gain_friendly': True,
            'current_price': 3500,
            'price_unit': 'kg'
        },
        {
            'name': 'Maize (Corn)',
            'local_name': 'Doodo',
            'category': 'grains',
            'description': 'Staple grain, rich in fiber',
            'calories': 365,
            'protein': 9.4,
            'carbohydrates': 74.3,
            'fiber': 7.3,
            'fat': 4.7,
            'sugar': 0.6,
            'glycemic_index': 52,
            'sodium': 35,
            'vitamin_c': 0,
            'iron': 2.7,
            'calcium': 7,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_gain_friendly': True,
            'current_price': 2500,
            'price_unit': 'kg'
        },
        {
            'name': 'Avocado',
            'local_name': 'Ovacado',
            'category': 'fruits',
            'description': 'High in healthy fats and fiber',
            'calories': 160,
            'protein': 2.0,
            'carbohydrates': 8.5,
            'fiber': 6.7,
            'fat': 14.7,
            'sugar': 0.7,
            'glycemic_index': 10,
            'sodium': 7,
            'vitamin_c': 10.0,
            'iron': 0.6,
            'calcium': 12,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'weight_gain_friendly': True,
            'current_price': 3000,
            'price_unit': 'piece'
        },
        {
            'name': 'Mango',
            'local_name': 'Muyembe',
            'category': 'fruits',
            'description': 'Sweet tropical fruit, rich in vitamin C',
            'calories': 60,
            'protein': 0.8,
            'carbohydrates': 15.0,
            'fiber': 1.6,
            'fat': 0.4,
            'sugar': 13.7,
            'glycemic_index': 51,
            'sodium': 1,
            'vitamin_c': 36.4,
            'iron': 0.2,
            'calcium': 11,
            'is_affordable': True,
            'diabetes_friendly': True,
            'current_price': 1500,
            'price_unit': 'kg'
        },
        {
            'name': 'Pineapple',
            'local_name': 'Nnanasi',
            'category': 'fruits',
            'description': 'Tropical fruit with digestive enzymes',
            'calories': 50,
            'protein': 0.5,
            'carbohydrates': 13.1,
            'fiber': 1.4,
            'fat': 0.1,
            'sugar': 9.9,
            'glycemic_index': 59,
            'sodium': 1,
            'vitamin_c': 47.8,
            'iron': 0.3,
            'calcium': 13,
            'is_affordable': True,
            'diabetes_friendly': True,
            'current_price': 2000,
            'price_unit': 'piece'
        },
        {
            'name': 'Fish (Tilapia)',
            'local_name': 'Engege',
            'category': 'proteins',
            'description': 'Lean protein source, rich in omega-3',
            'calories': 128,
            'protein': 26.0,
            'carbohydrates': 0,
            'fiber': 0,
            'fat': 2.7,
            'sugar': 0,
            'glycemic_index': 0,
            'sodium': 49,
            'vitamin_c': 0,
            'iron': 0.8,
            'calcium': 14,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'current_price': 8000,
            'price_unit': 'kg'
        },
        {
            'name': 'Chicken',
            'local_name': 'Enkoko',
            'category': 'proteins',
            'description': 'Lean protein, good for muscle building',
            'calories': 165,
            'protein': 31.0,
            'carbohydrates': 0,
            'fiber': 0,
            'fat': 3.6,
            'sugar': 0,
            'glycemic_index': 0,
            'sodium': 74,
            'vitamin_c': 0,
            'iron': 0.9,
            'calcium': 15,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'weight_gain_friendly': True,
            'current_price': 12000,
            'price_unit': 'kg'
        },
        {
            'name': 'Eggs',
            'local_name': 'Amagi',
            'category': 'proteins',
            'description': 'Complete protein source, affordable',
            'calories': 155,
            'protein': 13.0,
            'carbohydrates': 1.1,
            'fiber': 0,
            'fat': 11.0,
            'sugar': 1.1,
            'glycemic_index': 0,
            'sodium': 124,
            'vitamin_c': 0,
            'iron': 1.8,
            'calcium': 56,
            'is_affordable': True,
            'diabetes_friendly': True,
            'weight_loss_friendly': True,
            'weight_gain_friendly': True,
            'current_price': 1200,
            'price_unit': 'piece'
        }
    ]
    
    for food_data in ugandan_foods:
        food = FoodItem(**food_data)
        food.price_last_updated = datetime.utcnow()
        db.session.add(food)
    
    db.session.commit()
    print("Default food items initialized successfully!")

